# Generated by Django 2.2 on 2019-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60)),
                ('image', models.ImageField(upload_to='item_image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField()),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(choices=[('fr', 'Fruits'), ('vg', 'Vegetables'), ('tu', 'Tubers')], max_length=2)),
            ],
        ),
    ]
